/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdmissionRouteImport } from './routes/admission'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as RoutineRouteImport } from './routes/routine'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as TeacherLoginRouteImport } from './routes/teacher-login'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminModuleRouteImport } from './routes/admin.$module'
import { Route as AdminAdmissionsRouteImport } from './routes/admin.admissions'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as NoticesIndexRouteImport } from './routes/notices/index'
import { Route as NoticesNoticeIdRouteImport } from './routes/notices/$noticeId'
import { Route as AdminStudentsIdRouteImport } from './routes/admin.students.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionRoute = AdmissionRouteImport.update({
  id: '/admission',
  path: '/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutineRoute = RoutineRouteImport.update({
  id: '/routine',
  path: '/routine',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherLoginRoute = TeacherLoginRouteImport.update({
  id: '/teacher-login',
  path: '/teacher-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModuleRoute = AdminModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdmissionsRoute = AdminAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const NoticesIndexRoute = NoticesIndexRouteImport.update({
  id: '/notices/',
  path: '/notices/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesNoticeIdRoute = NoticesNoticeIdRouteImport.update({
  id: '/notices/$noticeId',
  path: '/notices/$noticeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsIdRoute = AdminStudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRouteWithChildren
  '/admission': typeof AdmissionRoute
  '/calendar': typeof CalendarRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/developer': typeof DeveloperRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/results': typeof ResultsRoute
  '/routine': typeof RoutineRoute
  '/teacher': typeof TeacherRoute
  '/teacher-login': typeof TeacherLoginRoute
  '/admin/$module': typeof AdminModuleRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/notices/$noticeId': typeof NoticesNoticeIdRoute
  '/admin/': typeof AdminIndexRoute
  '/notices/': typeof NoticesIndexRoute
  '/admin/students/$id': typeof AdminStudentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/achievements': typeof AchievementsRoute
  '/admission': typeof AdmissionRoute
  '/calendar': typeof CalendarRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/developer': typeof DeveloperRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/results': typeof ResultsRoute
  '/routine': typeof RoutineRoute
  '/teacher': typeof TeacherRoute
  '/teacher-login': typeof TeacherLoginRoute
  '/admin/$module': typeof AdminModuleRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/notices/$noticeId': typeof NoticesNoticeIdRoute
  '/admin': typeof AdminIndexRoute
  '/notices': typeof NoticesIndexRoute
  '/admin/students/$id': typeof AdminStudentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRouteWithChildren
  '/admission': typeof AdmissionRoute
  '/calendar': typeof CalendarRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/developer': typeof DeveloperRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/results': typeof ResultsRoute
  '/routine': typeof RoutineRoute
  '/teacher': typeof TeacherRoute
  '/teacher-login': typeof TeacherLoginRoute
  '/admin/$module': typeof AdminModuleRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/notices/$noticeId': typeof NoticesNoticeIdRoute
  '/admin/': typeof AdminIndexRoute
  '/notices/': typeof NoticesIndexRoute
  '/admin/students/$id': typeof AdminStudentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academics'
    | '/achievements'
    | '/admin'
    | '/admission'
    | '/calendar'
    | '/contact'
    | '/dashboard'
    | '/developer'
    | '/facilities'
    | '/gallery'
    | '/login'
    | '/results'
    | '/routine'
    | '/teacher'
    | '/teacher-login'
    | '/admin/$module'
    | '/admin/admissions'
    | '/admin/reports'
    | '/admin/settings'
    | '/notices/$noticeId'
    | '/admin/'
    | '/notices/'
    | '/admin/students/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academics'
    | '/achievements'
    | '/admission'
    | '/calendar'
    | '/contact'
    | '/dashboard'
    | '/developer'
    | '/facilities'
    | '/gallery'
    | '/login'
    | '/results'
    | '/routine'
    | '/teacher'
    | '/teacher-login'
    | '/admin/$module'
    | '/admin/admissions'
    | '/admin/reports'
    | '/admin/settings'
    | '/notices/$noticeId'
    | '/admin'
    | '/notices'
    | '/admin/students/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academics'
    | '/achievements'
    | '/admin'
    | '/admission'
    | '/calendar'
    | '/contact'
    | '/dashboard'
    | '/developer'
    | '/facilities'
    | '/gallery'
    | '/login'
    | '/results'
    | '/routine'
    | '/teacher'
    | '/teacher-login'
    | '/admin/$module'
    | '/admin/admissions'
    | '/admin/reports'
    | '/admin/settings'
    | '/notices/$noticeId'
    | '/admin/'
    | '/notices/'
    | '/admin/students/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicsRoute: typeof AcademicsRoute
  AchievementsRoute: typeof AchievementsRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdmissionRoute: typeof AdmissionRoute
  CalendarRoute: typeof CalendarRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DeveloperRoute: typeof DeveloperRoute
  FacilitiesRoute: typeof FacilitiesRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  ResultsRoute: typeof ResultsRoute
  RoutineRoute: typeof RoutineRoute
  TeacherRoute: typeof TeacherRoute
  TeacherLoginRoute: typeof TeacherLoginRoute
  NoticesNoticeIdRoute: typeof NoticesNoticeIdRoute
  NoticesIndexRoute: typeof NoticesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission': {
      id: '/admission'
      path: '/admission'
      fullPath: '/admission'
      preLoaderRoute: typeof AdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routine': {
      id: '/routine'
      path: '/routine'
      fullPath: '/routine'
      preLoaderRoute: typeof RoutineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-login': {
      id: '/teacher-login'
      path: '/teacher-login'
      fullPath: '/teacher-login'
      preLoaderRoute: typeof TeacherLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$module': {
      id: '/admin/$module'
      path: '/$module'
      fullPath: '/admin/$module'
      preLoaderRoute: typeof AdminModuleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admissions': {
      id: '/admin/admissions'
      path: '/admissions'
      fullPath: '/admin/admissions'
      preLoaderRoute: typeof AdminAdmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/notices/': {
      id: '/notices/'
      path: '/notices'
      fullPath: '/notices/'
      preLoaderRoute: typeof NoticesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices/$noticeId': {
      id: '/notices/$noticeId'
      path: '/notices/$noticeId'
      fullPath: '/notices/$noticeId'
      preLoaderRoute: typeof NoticesNoticeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students/$id': {
      id: '/admin/students/$id'
      path: '/students/$id'
      fullPath: '/admin/students/$id'
      preLoaderRoute: typeof AdminStudentsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminModuleRoute: typeof AdminModuleRoute
  AdminAdmissionsRoute: typeof AdminAdmissionsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminStudentsIdRoute: typeof AdminStudentsIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminModuleRoute: AdminModuleRoute,
  AdminAdmissionsRoute: AdminAdmissionsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminStudentsIdRoute: AdminStudentsIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicsRoute: AcademicsRoute,
  AchievementsRoute: AchievementsRoute,
  AdminRoute: AdminRouteWithChildren,
  AdmissionRoute: AdmissionRoute,
  CalendarRoute: CalendarRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DeveloperRoute: DeveloperRoute,
  FacilitiesRoute: FacilitiesRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  ResultsRoute: ResultsRoute,
  RoutineRoute: RoutineRoute,
  TeacherRoute: TeacherRoute,
  TeacherLoginRoute: TeacherLoginRoute,
  NoticesNoticeIdRoute: NoticesNoticeIdRoute,
  NoticesIndexRoute: NoticesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
